"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { Skeleton } from "@/components/ui/skeleton";
import { SessionContextPanel } from "@/components/session/session-context-panel";
import { EvolutionGraph } from "./evolution-graph";
import { FeedbackPanel } from "./feedback-panel";
import { GenerationStatus } from "./generation-status";
import { InteractiveActions } from "./interactive-actions";
import { PromptComposer } from "./prompt-composer";
import { SessionToolbar } from "./session-toolbar";
import { StrategyOutput } from "./strategy-output";
import type { ActionType } from "@/lib/schemas/agent";
import type { Feedback } from "@/lib/schemas/feedback";
import type { AgentOutput } from "@/lib/schemas/output";
import type { EvolutionResult, Playbook } from "@/lib/schemas/playbook";
import type { SessionProfile } from "@/lib/schemas/session";

interface SessionDetails {
  session: SessionProfile;
  outputs: AgentOutput[];
  feedback: Feedback[];
  evolution: Array<{ id: string; result: EvolutionResult; createdAt: string }>;
  activePlaybooks?: Playbook[];
}

export function StrategyWorkspace({ sessionId }: { sessionId: string }) {
  const [details, setDetails] = useState<SessionDetails | null>(null);
  const [activePlaybooks, setActivePlaybooks] = useState<Playbook[]>([]);
  const [currentOutput, setCurrentOutput] = useState<AgentOutput | null>(null);
  const [loading, setLoading] = useState(false);
  const [generationStep, setGenerationStep] = useState<string>();
  const [generationMessage, setGenerationMessage] = useState<string>();
  const autoGeneratedRef = useRef(false);

  async function load() {
    const response = await fetch(`/api/sessions/${sessionId}`);
    const data = (await response.json()) as SessionDetails;
    setDetails(data);
    setCurrentOutput(data.outputs[0] ?? null);
    setActivePlaybooks(data.activePlaybooks ?? []);
  }

  useEffect(() => {
    let alive = true;
    fetch(`/api/sessions/${sessionId}`)
      .then((response) => response.json())
      .then((data: SessionDetails) => {
        if (!alive) return;
        setDetails(data);
        setCurrentOutput(data.outputs[0] ?? null);
        setActivePlaybooks(data.activePlaybooks ?? []);
        // Автозапуск генерации если сессия новая (нет outputs) и есть тема
        if (data.outputs.length === 0 && data.session.focusTopic && !autoGeneratedRef.current) {
          autoGeneratedRef.current = true;
          generate("", data);
        }
      });
    return () => {
      alive = false;
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionId]);

  const markdown = useMemo(() => currentOutput?.markdown || currentOutput?.summary || "", [currentOutput]);

  async function generate(prompt: string, sessionDetails?: SessionDetails) {
    const activeDetails = sessionDetails ?? details;
    if (!activeDetails) return;
    setLoading(true);
    setGenerationStep("storage");
    setGenerationMessage("Запускаю генерацию");
    try {
      const response = await fetch("/api/generate/stream", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sessionId, prompt }),
      });
      if (!response.ok || !response.body) throw new Error("Ошибка генерации");
      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";
      let finalData: { output: AgentOutput; activePlaybooks: Playbook[]; error?: string } | null = null;
      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const chunks = buffer.split("\n\n");
        buffer = chunks.pop() || "";
        for (const chunk of chunks) {
          const event = chunk.match(/^event: (.+)$/m)?.[1];
          const dataLine = chunk.match(/^data: (.+)$/m)?.[1];
          if (!event || !dataLine) continue;
          const data = JSON.parse(dataLine) as { step?: string; message?: string; error?: string; output?: AgentOutput; activePlaybooks?: Playbook[] };
          if (event === "step") {
            setGenerationStep(data.step);
            setGenerationMessage(data.message);
          }
          if (event === "error") throw new Error(data.error || "Ошибка генерации");
          if (event === "done" && data.output && data.activePlaybooks) finalData = { output: data.output, activePlaybooks: data.activePlaybooks };
        }
      }
      if (!finalData) throw new Error("Генерация завершилась без результата");
      setCurrentOutput(finalData.output);
      setActivePlaybooks(finalData.activePlaybooks);
      toast.success("Стратегический материал сформирован");
      void load();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Ошибка генерации");
    } finally {
      setLoading(false);
      setGenerationStep(undefined);
      setGenerationMessage(undefined);
    }
  }

  async function runAction(actionType: ActionType) {
    if (!details || !currentOutput) return;
    setLoading(true);
    try {
      const response = await fetch("/api/action", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sessionId,
          outputId: currentOutput.id,
          actionType,
          currentContent: markdown,
          sessionProfile: details.session,
        }),
      });
      const data = (await response.json()) as { output: AgentOutput; activePlaybooks: Playbook[]; error?: string };
      if (!response.ok) throw new Error(data.error || "Действие не выполнено");
      setCurrentOutput(data.output);
      setActivePlaybooks(data.activePlaybooks);
      toast.success("Ответ обновлен интерактивным действием");
      void load();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Действие не выполнено");
    } finally {
      setLoading(false);
    }
  }

  async function sendFeedback(rating: number, tags: string[], comment: string) {
    if (!details || !currentOutput) return;
    setLoading(true);
    try {
      const response = await fetch("/api/feedback", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sessionId, outputId: currentOutput.id, rating, tags, comment }),
      });
      const data = (await response.json()) as { evolution: EvolutionResult; error?: string };
      if (!response.ok) throw new Error(data.error || "Не удалось сохранить обратную связь");
      setCurrentOutput(data.evolution.rewrittenAnswer);
      toast.success("Агент улучшил ответ и обновил правила");
      void load();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Не удалось сохранить обратную связь");
    } finally {
      setLoading(false);
    }
  }

  if (!details) {
    return (
      <div className="grid gap-4 xl:grid-cols-[300px_1fr_360px]">
        <Skeleton className="h-96 rounded-2xl" />
        <Skeleton className="h-96 rounded-2xl" />
        <Skeleton className="h-96 rounded-2xl" />
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <SessionToolbar
        session={details.session}
        onRenamed={(session) => {
          setDetails({ ...details, session });
        }}
      />
      <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
        <main className="min-w-0 space-y-4">
          <PromptComposer onGenerate={generate} loading={loading} />
          <GenerationStatus active={loading} currentStep={generationStep} message={generationMessage} />
          <StrategyOutput output={currentOutput} />
        </main>
        <aside className="space-y-4 xl:sticky xl:top-20 xl:self-start">
          <SessionContextPanel session={details.session} playbooks={activePlaybooks} />
          <InteractiveActions disabled={!currentOutput} loading={loading} onAction={runAction} />
          <FeedbackPanel disabled={!currentOutput} loading={loading} onFeedback={sendFeedback} />
          <EvolutionGraph items={details.evolution} />
        </aside>
      </div>
    </div>
  );
}
